version: '3.9'

services:
  oracle:
    image: gvenzl/oracle-free:latest
    container_name: oracle23c
    ports:
      - "1521:1521"
    env_file:
      - .env
    environment:
      - ORACLE_PASSWORD=${ORACLE_PASSWORD}
      - ORACLE_CHARACTERSET=AL32UTF8
      - ORACLE_NLS_CHARACTERSET=AL32UTF8
    volumes:
      - ./backup:/opt/backup
      - ./init.sh:/docker-entrypoint-initdb.d/init.sh:ro
      - ./data:/opt/oracle/oradata  # <-- Adicionado: volume persistente seguro
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G
    shm_size: '2gb'
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
      memlock:
        soft: -1
        hard: -1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "sqlplus", "-L", "system/${ORACLE_PASSWORD}@//localhost:1521/FREEPDB1", "AS", "SYSDBA"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s