version: '3.9'

services:
  oracle:
    image: gvenzl/oracle-free:latest
    container_name: oracle23c
    platform: linux/amd64  # Força a plataforma para evitar problemas de compatibilidade no Windows
    ports:
      - "1521:1521"
    env_file:
      - .env
    environment:
      - ORACLE_PASSWORD=${ORACLE_PASSWORD}
      - ORACLE_CHARACTERSET=AL32UTF8
      - ORACLE_NLS_CHARACTERSET=AL32UTF8
    volumes:
      - type: bind
        source: ./backup
        target: /opt/backup
      - type: bind
        source: ./init.sh
        target: /docker-entrypoint-initdb.d/init.sh
        read_only: true
      - type: bind
        source: ./data
        target: /opt/oracle/oradata
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G
    shm_size: '2gb'
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
      memlock:
        soft: -1
        hard: -1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "sqlplus", "-L", "system/${ORACLE_PASSWORD}@//localhost:1521/FREEPDB1", "AS", "SYSDBA"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s
    command: >
      bash -c "
        /etc/init.d/oracle-xe-23c start &&
        sleep 30 &&
        chmod +x /docker-entrypoint-initdb.d/init.sh &&
        /docker-entrypoint-initdb.d/init.sh &&
        tail -f /opt/oracle/diag/rdbms/free/FREE/trace/alert_FREE.log
      "